version: '3.9'

services:
  api:
    image: node:16-alpine3.11
    working_dir: /app
    volumes:
      - ./:/app
    command: sh -c "npm i && npm run dev"
    ports:
      - 8080:8080

  database:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: db
    ports:
      - 27017:27017